name: Deploy to QA

on:
  push:
    branches: "main"

jobs:

  publish-image:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Main
        uses: actions/checkout@main
      - name: Publish Image
        id: publish
        uses: elgohr/Publish-Docker-Github-Action@v5
        with:
          registry: ghcr.io
          name: nfcopier/portfolio-web-ui
          username: ${{ github.actor }}
          password: ${{ secrets.GITHUB_TOKEN }}
          tags: beta-${{github.run_number}}
    outputs:
      tag: ${{ steps.publish.outputs.tag }}

  deploy-to-qa:
    runs-on: ubuntu-latest
    needs: publish-image
    steps:
      - name: Checkout Main
        uses: actions/checkout@main
      - name: NPM Install
        run: npm ci
      - name: Synth
        run: npx ts-node infrastructure/KubeApp.ts ${{ needs.publish-image.outputs.tag }}
      - name: Deploy
        uses: actions-hub/kubectl@master
        env:
          KUBE_CONFIG: ${{ secrets.KUBE_CONFIG }}
        with:
          args: apply -f ./infrastructure
